# Generated by Django 5.1.5 on 2025-02-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_note_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
