# Generated by Django 5.1.5 on 2025-02-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_note_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='checkout',
            new_name='status',
        ),
    ]
